apiVersion: v1
kind: Pod
metadata:
  name: app-one
  # kubectl get pods -n stissera
  namespace: stissera
  # kubectl get pods -l role=prod
  labels:
    role: prod
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP