apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_1
  template:
    metadata:
      labels:
        app: app_1
    spec:
      containers:
      - name: app-1
        image: paulbouwer/hello-kubernetes:1.9
        env:
          - name: MESSAGE
          value: "Hello from APP1"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
spec:
  selector:
    app: app_1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app_2
  template:
    metadata:
      labels:
        app: app_2
    spec:
      containers:
      - name: app-2
        image: paulbouwer/hello-kubernetes:1.9
        env:
          - name: MESSAGE
          value: "Hello from APP2"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-2-service
spec:
  selector:
    app: app_2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_3
  template:
    metadata:
      labels:
        app: app_3
    spec:
      containers:
      - name: app-3
        image: paulbouwer/hello-kubernetes:1.9
        env:
          - name: MESSAGE
          value: "Hello from APP3"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-3-service
spec:
  selector:
    app: app_3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Ensure NGINX Ingress Controller is installed
spec:
  rules:
  - host: "app1.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-1-service
            port:
              number: 80
  - host: "app2.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-2-service
            port:
              number: 80

  # Default service comme demande dans le sujet
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-3-service
            port:
              number: 80
