Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"

    config.vm.define "swalterS" do |server|
        server.vm.hostname = "swalterS"
        server.vm.network "private_network", ip: "192.168.42.110"
        server.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.name = "swalterS"
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell", inline: <<-SHELL
        sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
        service ssh restart
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -s -
        echo $(sudo cat /var/lib/rancher/k3s/server/node-token) > /vagrant/.token
        SHELL
        
        end
    end

    config.vm.define "swalterSW" do |worker|
        worker.vm.hostname = "swalterSW"
        worker.vm.network "private_network", ip: "192.168.42.111"
        worker.vm.provider "virtualbox" do |v|
            v.name = "swalterSW"
            v.memory = 1024
            v.cpus = 1
        end
        worker.vm.provision "shell", inline: <<-SHELL
        sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
        service ssh restart
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=$(cat /vagrant/.token) INSTALL_K3S_EXEC="--flannel-iface eth1" sh -s -
        SHELL
        
        end
    end
    
end
