Vagrant.configure('2') do |config|
	config.vm.box = 'loundor/debian'
	config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: false, nfs_version: 4, nfs_udp: false)	
	#config.vm.network 'private_network', ip: '192.168.10.170', netmask: '255.255.255.0'
	#config.vm.network 'private_network', ip: '192.168.1.171'
	#config.vm.network 'public_network', ip: '192.168.12.170'
	config.vm.network 'private_network', ip: '192.168.56.110'
	config.vm.hostname = 'stisseraS'		  
	config.vm.provider :vmware_esxi do |esxi|
		esxi.esxi_hostname = 'vm.loundor.com'
		esxi.esxi_username = 'inception'
		esxi.esxi_password = 'prompt:'
		esxi.esxi_hostport = 1422
		esxi.esxi_virtual_network = ['PC Network','Inception']
		esxi.esxi_disk_store = 'OS'
		esxi.guest_name = 'Master'
		esxi.guest_memsize = '2048'
		esxi.guest_numvcpus = '1'
		esxi.guest_nic_type = 'vmxnet3'
		esxi.guest_guestos = 'other3xlinux-64'
		esxi.debug = 'true'
	end
	config.vm.provision "shell", inline: <<-SHELL
		export DEBIAN_FRONTEND=noninteractive
		sudo apt-get update
		sudo apt-get upgrade -y
		sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		sudo systemctl restart sshd
		curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --flannel-iface eth1" sh -s -
		sudo install.sh
	SHELL
end